name = 'auto-readme-worker'
main = "src/worker.js"
compatibility_date = "2024-12-27"
workers_dev = true
preview_urls = false

[build]
command = "npm install"

[vars]
ALLOWED_ORIGINS = "https://auto-readme.netlify.app"

[observability.logs]
enabled = true